name: GitHub Actions Demo
run-name: For-practice
on: [push]

#env:
 # IMAGE_NAME: adityavishwakarma31/django-todo-app
jobs:
  build:
    runs-on: self-hosted
    steps:
       - name: pull repo
         uses: actions/checkout@v4
       - name: Build images
         run: docker build -t myapp .
       - name: createfolder
         run: docker images
